### ISSUE TITLE
ag-grid license

### ISSUE THREAD

**Issue by jfstephe** [ceolter/ag-grid-aurelia#1]
Hi,
Can you clarify something please? The ag-grid is not MIT for all uses. Your library and license agreement seems to effectively hide this. Can you add clarity to your page or correct me if I'm wrong?
Thanks,
John

**Comment by ceolter** [comment]
ag-grid is free
ag-grid-enterprise is not free

ag-grid-aurelia is free and can be used with either, however if you use with ag-grid-enterprise, then you need an enterprise license.
