### ISSUE TITLE
hide.bind="true" is not working to hide columns

### ISSUE THREAD

**Issue by don-bluelinegrid** [ceolter/ag-grid-aurelia#16]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-aurelia/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Adding ```hide.bind="true"``` to a declarative column definition is not working to hide columns.

**Expected behavior**
Should hide the columns, as documented.

**Minimal reproduction of the problem with instructions**

```
        <ag-grid-column if.bind="showColumn('message')" header-name="${'alerts.notifications.message' | t}" field="message" hide.bind="true" filter.bind="getTextSearchFilter()"></ag-grid-column>
```
**What is the motivation / use case for changing the behavior?**
I need to hide columns that are used in parent/child groups, so that the group column text will be searchable by QuickFilter.

**Please tell us about your environment:**
MacOS

* **ag-grid-aurelia version:** 9.0.0

* **ag-Grid/ag-Grid-Enterprise version:** 2.0.X

* **Aurelia version:** 2.0.X

* **Browser:** all

* **Language:** TypeScript

**Comment by don-bluelinegrid** [comment]
This is still not working in version 12.0.0.  
`hide.bind="true"` or `hide="true"` does not have any effect.

Any update?

**Comment by mroseboom** [comment]
@don-bluelinegrid This is because the `hide` custom attribute from [aurelia-templating-resources](https://github.com/aurelia/templating-resources/blob/master/src/hide.js) interferes with the `hide` colDef option.

**Comment by seanlandsman** [comment]
I've added a new column property called "hideCol" - this will be mapped to "hide" under the covers and work as expected.

I'll also update the docs to reflect this difference in aurelia
