### ISSUE TITLE
Missing column attributes

### ISSUE THREAD

**Issue by AubieDawg92** [ceolter/ag-grid-aurelia#20]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-aurelia/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
agGridColumn does not support the following properties:

headerCheckboxSelection
headerCheckboxSelectionFilteredOnly

**Expected behavior**
agGridColumn should support those attributes

**What is the motivation / use case for changing the behavior?**
Should be able to use the built-in functionality for header checkboxes.

**Comment by seanlandsman** [comment]
Hi - this has now been fixed and will be available in the next release
