### ISSUE TITLE
v13 update bad aurelia dependencies

### ISSUE THREAD

**Issue by don-bluelinegrid** [ceolter/ag-grid-aurelia#22]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-aurelia/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
npm update fails
**Expected behavior**
npm update should not fail
**Minimal reproduction of the problem with instructions**
After updating in npm from v12 to v13, the update fails due to unmet peer dependencies.
See below:
```
MacBook-Pro:gc-2-dev donpeterkofsky$ npm update ag-grid --save
npm WARN saveError Problems were encountered
npm WARN saveError Please correct and try again.
npm WARN saveError peer invalid: aurelia-framework@1.0.x, required by ag-grid-aurelia@13.0.2
npm WARN saveError peer invalid: ag-grid@13.0.2, required by ag-grid-aurelia@13.0.2
npm WARN saveError extraneous: jquery-ui@1.12.1 /Users/donpeterkofsky/Documents/gc-2-dev/node_modules/jquery-ui
blueline-grid-gridcommand@1.0.0 /Users/donpeterkofsky/Documents/gc-2-dev
├── UNMET PEER DEPENDENCY ag-grid@13.1.0
└── UNMET PEER DEPENDENCY aurelia-framework@1.1.2

npm WARN ag-grid-aurelia@13.0.2 requires a peer of aurelia-framework@1.0.x but none was installed.
npm WARN ag-grid-aurelia@13.0.2 requires a peer of ag-grid@13.0.2 but none was installed.
npm ERR! code 1

```
It appears that ag-grid-aurelia v13 is strictly requiring an Aurelia version of 1.0.x, which was not the case previously.  So, my installed version of 1.1.x is not being accepted.

**What is the motivation / use case for changing the behavior?**
Update/build should work with current/latest Aurelia version.

**Please tell us about your environment:**
NA

* **ag-grid-aurelia version:** 13.0.X

* **ag-Grid/ag-Grid-Enterprise version:** 13.0.X
* **Aurelia version:** 1.1.2

* **Browser:** NA

* **Language:** TypeScript

**Comment by mroseboom** [comment]
@seanlandsman I think the following would be enough and a simple fix, your thoughts? If so i'll make a pull-request.

```typescript
// change this
"aurelia-framework": "1.0.x",
// in to
"aurelia-framework": "1.x",
```

**Comment by seanlandsman** [comment]
@don-bluelinegrid @mroseboom I'll take a look at this today or tomorrow.

thanks

**Comment by seanlandsman** [comment]
@don-bluelinegrid @mroseboom I was a bit tied up at the end of last week with other stuff - looking at this this week now

**Comment by seanlandsman** [comment]
This has now been rectified and will be available in the next few days

thanks

**Comment by don-bluelinegrid** [comment]
@seanlandsman 

Thanks, Sean.

Could you please post an update here when it's available?

Don

**Comment by davismj** [comment]
So we were seeing an issue where ag-grid-aurelia was trying to load aurelia-framework@1.0.8. And update on ag-grid-aurelia should solve that?
