### ISSUE TITLE
Changing data does not update the grid data

### ISSUE THREAD

**Issue by elitemike** [ceolter/ag-grid-aurelia#3]
Simple grid bound to an array with one property called name.  The value of data[0].name can be changed externally via an input box but the grid won't update. I have this field set to editable. When you edit from the grid, 2 way binding works properly and updates the standalone input.   If you change the input boxes value then double click the table cell you see the proper value there and it will hold even if you hit escape to cancel the edit.
` 
<ag-grid-aurelia grid-options.bind="gridOptions" 
                        class="ag-fresh"
                       row-height.bind="48"                      
                       grid-ready.call="onGridReady()"
                    >      
          <ag-grid-column header-name="Name" field="name" editable.bind="true" >
          </ag-grid-column>          
        </ag-grid-column>
      </ag-grid-aurelia>
 <input  value.bind="data[0].name"/>
`

`
     this.gridOptions = <GridOptions>{};
     this.gridOptions.rowData = this.data; 
`
Is this a bug or is this by design? If it is by design is there a way to force the display field to update as the underlying data changes?

**Comment by swalters** [comment]
By design.  See docs to refresh.  https://www.ag-grid.com/javascript-grid-refresh/

**Comment by elitemike** [comment]
I haven't studied the code yet, how hard would it be to add an option that when a property is updated to trigger a type of reload?  One scenario I have has data pushed in to a grid but doesn't update too often, most of the time a field that tracks status is all that is updated.  I can certainly just call the refresh view, but it would be "nice" to just update the aurelia property and be done in some cases.  I prefer this grid implementation over the kendo-ui one.

**Comment by cindoum** [comment]
That seem like a big problem. We are moving to aurelia and i wanted to try ag-grid. The fact that there is no two-way binding is a deal breaker. We dont want to handle each data update. 

Anyone found a solution?
