### ISSUE TITLE
feat(dateComponent): use customElement within/as dateComponent

### ISSUE THREAD

**Issue by mroseboom** [ceolter/ag-grid-aurelia#5]
**I'm submitting a ...**
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-aurelia/blob/master/CONTRIBUTING.md#question
```

**What is the motivation / use case for changing the behavior?**
Is it (maybe already) possible to use a customElement within/as a DateComponent, just like a cellRenderer?

* **ag-grid-aurelia version:** 8.0.0

* **ag-Grid/ag-Grid-Enterprise version:** 8.0.1

**Comment by seanlandsman** [comment]
Hi,

Thanks for raising this. I've raised AG-777 our side to track this - you can view its progress on our pipeline page here: https://www.ag-grid.com/ag-grid-pipeline/

We'll update this thread with updates as soon as we have any.

thanks

**Comment by seanlandsman** [comment]
Hi @mroseboom - this has now been added and will be available in our next release

**Comment by mroseboom** [comment]
@seanlandsman Thanks, awesome work!
